// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSy3Q_d3EWjEWdAu_OcqR2V2eI1tGheJo',
    appId: '1:73615908589:web:3560089378f6de38efb6e4',
    messagingSenderId: '73615908589',
    projectId: 'attendance-app-15c8b',
    authDomain: 'attendance-app-15c8b.firebaseapp.com',
    storageBucket: 'attendance-app-15c8b.firebasestorage.app',
    measurementId: 'G-KCMJKB3TGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAomIgTzR7dfy9cejF4W1XCRGE_bbDNrF0',
    appId: '1:73615908589:android:e30519115a0a6b1cefb6e4',
    messagingSenderId: '73615908589',
    projectId: 'attendance-app-15c8b',
    storageBucket: 'attendance-app-15c8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKvyFTG7JHZYbLRA9-NUdmKERvkayqupk',
    appId: '1:73615908589:ios:7cc4ff9bf3c77a62efb6e4',
    messagingSenderId: '73615908589',
    projectId: 'attendance-app-15c8b',
    storageBucket: 'attendance-app-15c8b.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKvyFTG7JHZYbLRA9-NUdmKERvkayqupk',
    appId: '1:73615908589:ios:7cc4ff9bf3c77a62efb6e4',
    messagingSenderId: '73615908589',
    projectId: 'attendance-app-15c8b',
    storageBucket: 'attendance-app-15c8b.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSy3Q_d3EWjEWdAu_OcqR2V2eI1tGheJo',
    appId: '1:73615908589:web:08869e4f4fae41c1efb6e4',
    messagingSenderId: '73615908589',
    projectId: 'attendance-app-15c8b',
    authDomain: 'attendance-app-15c8b.firebaseapp.com',
    storageBucket: 'attendance-app-15c8b.firebasestorage.app',
    measurementId: 'G-HTG2BRB67B',
  );

}